name: dnn-cuda
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - torch==2.5.1 --index-url https://download.pytorch.org/whl/cu118
    - torchvision==0.20.1 --index-url https://download.pytorch.org/whl/cu118
    - torchaudio==2.5.1 --index-url https://download.pytorch.org/whl/cu118
    - ipykernel
    - jupyter
    - notebook
    - matplotlib
    - numpy
    - scipy
    - pandas
    - polars
    - scikit-learn
