name: dnn-py312
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - torch==2.5.1+cu121
    - torchvision==0.20.1+cu121
    - torchaudio==2.5.1+cu121
    - ipykernel
    - jupyter
    - notebook
    - matplotlib
    - numpy
    - scipy
    - pandas
    - polars
